version: '3.8'

services:
  app:
    build:
      context: .
      secrets:
        - "ACCESS_KEY"
        - "ACCESS_TOKEN"
      dockerfile: Dockerfile
    container_name: nestjs-vite-template
    environment:
      NODE_ENV: production
    env_file:
      - ./apps/api/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      
secrets:
  ACCESS_KEY:
    environment: "ACCESS_KEY"
  ACCESS_TOKEN:
    environment: "ACCESS_TOKEN"